FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/safety-hub-lqzg4/firestore/indexes?create_composite=ClRwcm9qZWN0cy9zYWZldHktaHViLWxxemc0L2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9zdWdnZXN0aW9ucy9pbmRleGVzL18QARoKCgZ1c2VySWQQARoICgRkYXRlEAIaDAoIX19uYW1lX18QAg